version: 0.2

phases:
  install:
    commands:
      - echo "Install Terraform"
      - curl -sLo tf.zip https://releases.hashicorp.com/terraform/1.7.5/terraform_1.7.5_linux_amd64.zip
      - unzip -q tf.zip && mv terraform /usr/local/bin/ && terraform -version

  pre_build:
    commands:
      - set -e
      - REGION=ap-southeast-2
      - REPO=mini-net9-lambda
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - IMAGE_TAG=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION:-manual} | cut -c1-7)
      - IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO:$IMAGE_TAG

      # ECR 仓库（不存在就创建），并登录
      - aws ecr describe-repositories --repository-names $REPO --region $REGION >/dev/null 2>&1 || aws ecr create-repository --repository-name $REPO --region $REGION
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo "Build & Push image -> $IMAGE_URI"
      - docker build -t $REPO .
      - docker tag $REPO:latest $IMAGE_URI
      - docker push $IMAGE_URI

  post_build:
    commands:
      - echo "Wire image_uri into Terraform (sed replace)"
      - sed -i "s|REPLACE_WITH_YOUR_ECR_IMAGE_URI|$IMAGE_URI|g" infra/main.tf

      - echo "Terraform init (local state)"
      - terraform -chdir=infra init

      # === Import existing resources into local state（若已存在则导入）===
      # IAM Role
      - if aws iam get-role --role-name mini-net9-lambda-role >/dev/null 2>&1; then
        ROLE_ARN=$(aws iam get-role --role-name mini-net9-lambda-role --query Role.Arn --output text);
        terraform -chdir=infra import -no-color -input=false aws_iam_role.lambda "$ROLE_ARN" || true;
        fi
      # Lambda Function
      - if aws lambda get-function --function-name mini-net9-image >/dev/null 2>&1; then
        FN_ARN=$(aws lambda get-function --function-name mini-net9-image --query Configuration.FunctionArn --output text);
        terraform -chdir=infra import -no-color -input=false aws_lambda_function.fn "$FN_ARN" || true;
        fi
      # Function URL
      - if aws lambda get-function-url-config --function-name mini-net9-image >/dev/null 2>&1; then
        terraform -chdir=infra import -no-color -input=false aws_lambda_function_url.url mini-net9-image || true;
        fi
      # ===============================================================

      - echo "Terraform apply"
      - terraform -chdir=infra apply -auto-approve -no-color

artifacts:
  files:
    - infra/main.tf
